apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-event-gateway
  namespace: discord-event-gateway
  labels:
    app: discord-event-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-event-gateway
  template:
    metadata:
      labels:
        app: discord-event-gateway
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "discord-gateway-api-role"
        vault.hashicorp.com/agent-inject-secret-db: "secret/discord-gateway-api/db"
        vault.hashicorp.com/agent-inject-file-db: "db.yaml"
        vault.hashicorp.com/agent-inject-template-db: |
          {{- with secret "secret/discord-gateway-api/db" -}}
          spring:
            datasource:
              url: "jdbc:postgresql://{{ .Data.data.host }}:{{ .Data.data.port }}/{{ .Data.data.dbname }}"
              username: "{{ .Data.data.username }}"
              password: "{{ .Data.data.password }}"
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-s3: "secret/discord-gateway-api/s3"
        vault.hashicorp.com/agent-inject-file-s3: "s3.yaml"
        vault.hashicorp.com/agent-inject-template-s3: |
          {{- with secret "secret/discord-gateway-api/s3" -}}
          gateway:
            garage:
              endpoint: "{{ .Data.data.endpoint }}"
              bucket: "{{ .Data.data.bucket }}"
          GARAGE_ACCESS_KEY: "{{ .Data.data.access_key_id }}"
          GARAGE_SECRET_KEY: "{{ .Data.data.secret_access_key }}"
          {{- end -}}
    spec:
      serviceAccountName: discord-gateway-api
      containers:
        - name: gateway
          image: localhost:32000/discord-event-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "consul.consul.svc.cluster.local"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "8500"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "4"
              memory: 4Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 4
      restartPolicy: Always
