apiVersion: v1
kind: Service
metadata:
  name: discord-event-gateway
  namespace: discord-event-gateway
  labels:
    app: discord-event-gateway
spec:
  selector:
    app: discord-event-gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
