-- H2: drop and recreate bot_command tables with correct schema (in-memory, no data loss risk)
DROP TABLE IF EXISTS GATEWAY.bot_command_log;
DROP TABLE IF EXISTS GATEWAY.bot_command;

CREATE TABLE GATEWAY.bot_command (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_name        VARCHAR(64)  NOT NULL,
    guild_id            VARCHAR(20),
    bot_id              VARCHAR(20),
    discord_command_id  VARCHAR(20),
    description         VARCHAR(256),
    prefix              VARCHAR(8)   NOT NULL DEFAULT 'SLASH'
                            CHECK (prefix IN ('SLASH', 'DOT')),
    parameters          CLOB         NOT NULL DEFAULT '[]',
    version             INT          NOT NULL DEFAULT 1,
    is_deleted          BOOLEAN      NOT NULL DEFAULT false,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (command_name, guild_id, bot_id, prefix)
);

CREATE TABLE GATEWAY.bot_command_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id       BIGINT       REFERENCES GATEWAY.bot_command(id),
    event_type       VARCHAR(16)  NOT NULL
                         CHECK (event_type IN ('REGISTERED', 'UPDATED', 'DELETED', 'CREATED', 'EXECUTED', 'FAILED')),
    guild_id         VARCHAR(20),
    bot_id           VARCHAR(20),
    discord_success  BOOLEAN,
    discord_error    TEXT,
    recorded_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
